# These are supported funding model platforms

#github: Swaroop44ops
#community_bridge: Musical-Instruments-store
#open_collective: Swaroop44ops
#ko_fi: Swaroop44ops
#tidelift: npm/babel
#liberapay: Swaroop44ops
#issuehunt: Swaroop44ops
#otechie: Swaroop44ops
#custom: github.com

